# -*- coding: utf-8 -*-
"""Flipkart Review Sentiment Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1suaDaw7_B8a5nmvE1t7eGH0ln7r9gO_p

# **Importing Libraries and Datasets**

The libraries used are :

1. **Pandas :** For importing the dataset.
2. **Scikit-learn :** For importing the model, accuracy module, and TfidfVectorizer.
3. **Warning :** To ignore all the warnings
4. **Matplotlib :** To plot the visualization. Also used Wordcloud for that.
5. **Seaborn :** For data visualization.
"""

import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import re
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt
from wordcloud import WordCloud

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
nltk.download('punkt')

data = pd.read_csv('flipkart_data.csv')
data.head()

"""#**Preprocessing and cleaning the reviews**

"""

# unique ratings
pd.unique(data['rating'])

sns.countplot(data=data,
			x='rating',
			order=data.rating.value_counts().index)

# rating label(final)
pos_neg = []
for i in range(len(data['rating'])):
	if data['rating'][i] >= 5:
		pos_neg.append(1)
	else:
		pos_neg.append(0)

data['label'] = pos_neg

from tqdm import tqdm


def preprocess_text(text_data):
	preprocessed_text = []

	for sentence in tqdm(text_data):
		# Removing punctuations
		sentence = re.sub(r'[^\w\s]', '', sentence)

		# Converting lowercase and removing stopwords
		preprocessed_text.append(' '.join(token.lower()
										for token in nltk.word_tokenize(sentence)
										if token.lower() not in stopwords.words('english')))

	return preprocessed_text

preprocessed_review = preprocess_text(data['review'].values)
data['review'] = preprocessed_review

data.head()

"""# **Analysis of the Dataset**

"""

data["label"].value_counts()

consolidated = ' '.join(
	word for word in data['review'][data['label'] == 1].astype(str))
wordCloud = WordCloud(width=1600, height=800,
					random_state=21, max_font_size=110)
plt.figure(figsize=(15, 10))
plt.imshow(wordCloud.generate(consolidated), interpolation='bilinear')
plt.axis('off')
plt.show()

"""# **Converting text into Vectors**

"""

cv = TfidfVectorizer(max_features=2500)
X = cv.fit_transform(data['review'] ).toarray()

X

"""# **Model training, Evaluation, and Prediction**"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, data['label'],
													test_size=0.33,
													stratify=data['label'],
													random_state = 42)

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

model = DecisionTreeClassifier(random_state=0)
model.fit(X_train,y_train)

#testing the model
pred = model.predict(X_train)
print(accuracy_score(y_train,pred))

from sklearn import metrics
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train,pred)

cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix = cm,
											display_labels = [False, True])

cm_display.plot()
plt.show()